### ISSUE TITLE
Use JavaScript API instead of iframe

### ISSUE THREAD

**Issue by zenorocha** [social-elements/twitter-button#5]
https://dev.twitter.com/web/tweet-button#ways-to-add-the-tweet-button-to-your-website

**Comment by Nevraeka** [comment]
From what @deebloo & I discussed yesterday, using the JavaScript API creates an iframe of it's own as a wrapper. Not sure if this is worth doing if that is the case

**Comment by deebloo** [comment]
It is still worth it. the iframe isn't the issue (to me). It is creating the buttons the way Twitter recommends you create buttons.

**Comment by Nevraeka** [comment]
if that is the case - go for it!

**Comment by deebloo** [comment]
done and sitting in a pull request :)

**Comment by deebloo** [comment]
His issue should be closed now correct?

**Comment by deebloo** [comment]
*This

**Comment by deebloo** [comment]
@Nevraeka i believe this issue is closed now
